genotype_phenotype = {
	'Agouti': 'A.-,C.-,D.-,E.-,G.-,P.-',
	'Argente Golden': 'A.-,C.C,D.-,E.-,G.-,p.p',
	'Argente Cream': 'x',
	'Grey Agouti': 'x',
	'Ivory Cream': 'x',
	'Dark Eyed Honey': 'x',
	'Red Eyed Honey': 'x',
	'Polar Fox ': 'x',
	'Red Eyed Polar Fox': 'x',
	'Black': 'x',
	'Blue': 'x',
	'Slate': 'x',
	'Lilac': 'x',
	'Dove': 'x',
	'Ruby Eyed White': 'x',
	'Nutmeg': 'x',
	'Argente Nutmeg': 'x',
	'Silver Nutmeg': 'x',
	'Schimmel': 'x',
	'Red Eyed Schimmel  ': 'x',
	'Topas': 'x',
	'Colourpoint Grey Agouti': 'x',
	'Burmese': 'x',
	'Siamese': 'x',
	'Sapphire': 'x',
	'Colourpoint Nutmeg': 'x',
	'Colourpoint Silver Nutmeg': 'x',
	'Dark Tailed White': 'x',
	'Pink Eyed White': 'x',
}
