genotype_phenotype = {
	'Agouti': 'A.-,C.-,D.-,E.-,G.-,P.-',
	'Argente Golden': 'A.-,C.C,D.-,E.-,G.-,p.p',
	'Agouti': 'A.-,C.-,D.-,E.-,G.-,P.-',
	'Agouti': 'A.-,C.-,D.-,E.-,G.-,P.-',
	'Agouti': 'A.-,C.-,D.-,E.-,G.-,P.-',
	'Agouti': 'A.-,C.-,D.-,E.-,G.-,P.-',
	'Agouti': 'A.-,C.-,D.-,E.-,G.-,P.-',
	'Agouti': 'A.-,C.-,D.-,E.-,G.-,P.-',
	'Agouti': 'A.-,C.-,D.-,E.-,G.-,P.-',
	'Agouti': 'A.-,C.-,D.-,E.-,G.-,P.-',
	'Agouti': 'A.-,C.-,D.-,E.-,G.-,P.-',
	'Agouti': 'A.-,C.-,D.-,E.-,G.-,P.-',
	'Agouti': 'A.-,C.-,D.-,E.-,G.-,P.-',
	'Agouti': 'A.-,C.-,D.-,E.-,G.-,P.-',
	'Agouti': 'A.-,C.-,D.-,E.-,G.-,P.-',
	'Agouti': 'A.-,C.-,D.-,E.-,G.-,P.-',
	'Agouti': 'A.-,C.-,D.-,E.-,G.-,P.-',
	'Agouti': 'A.-,C.-,D.-,E.-,G.-,P.-',
	'Agouti': 'A.-,C.-,D.-,E.-,G.-,P.-',
	'Agouti': 'A.-,C.-,D.-,E.-,G.-,P.-',
}
